version: "3.9"

services:
  postgres_db:
    image: postgres:14.1
    container_name: amigoscode-email-register-postgresDB
    volumes:
      - amigoscode_email_register_data:/var/lib/postgresql/data
    env_file:
      - ./.postgres.env
    ports:
      - "5600:5432"
  maildev:
        ports:
            - '1080:1080'
            - '1025:1025'
        image: maildev/maildev

volumes:
  amigoscode_email_register_data:
